from __future__ import annotations

from typing import Protocol


class VectorStore(Protocol):
    def initialize(self) -> None: ...
    def doc_by_path(self, path: str) -> dict | None: ...
    def upsert_doc(
        self,
        doc_id: str,
        path: str,
        hash: str,
        mtime: float,
        chunks: list[tuple[str, list[float]]],
        model: str,
    ) -> None: ...
    def query(self, vector: list[float], k: int, model: str) -> list[dict]: ...
    def delete_doc(self, doc_id: str) -> None: ...
    def list_docs(self) -> list[dict]: ...
    def stats(self) -> dict: ...
