from __future__ import annotations

from typing import Protocol


class VectorStore(Protocol):
    def initialize(self) -> None: ...
    def doc_by_path(self, path: str) -> dict | None: ...
    def doc_by_id(self, doc_id: str) -> dict | None: ...
    def upsert_doc(
        self,
        doc_id: str,
        path: str,
        version: str,
        mtime: float,
        chunks: list[tuple[str, list[float]]],
        model: str,
        origin: str = "local",
    ) -> None: ...
    def query(self, vector: list[float], k: int, model: str) -> list[dict]: ...
    def delete_doc(self, doc_id: str) -> None: ...
    def delete_missing(self, origin: str, seen_ids: set[str]) -> int: ...
    def list_docs(self, origin: str | None = None) -> list[dict]: ...
    def stats(self, origin: str | None = None) -> dict: ...
